name: React build

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/react.yml"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/react.yml"

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      CI: false
    strategy:
      matrix:
        node-version: [18.x]

    defaults:
      run:
        working-directory: "./react.yml"

    steps:
      - uses: actions/checkout@v3

      - name: Install Npm
        run: npm install

      - name: Install dependencies # yarn install 추가
        run: npm install

      - name: Build # React Build
        run: npm run build
